version: "3"

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build: .
    command: sh -c "pipenv run python3 manage.py makemigrations && 
      pipenv run python3 manage.py migrate && 
      pipenv run python3 manage.py collectstatic &&
      pipenv run gunicorn -b web:8000 --log-file ./logs/log --workers 3 config.wsgi:application"
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db