version: "3"

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build: .
    # command: pipenv run python3 manage.py migrate
    # command: pipenv run python3 manage.py runserver 8000
    # command: pipenv run gunicorn -b 0.0.0.0:8000 config.wsgi:application
    command: sh -c "pipenv run python3 manage.py makemigrations && 
      pipenv run python3 manage.py migrate && 
      pipenv run python3 manage.py collectstatic &&
      pipenv run gunicorn -b web:8000 config.wsgi:application"
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db