version: "3"

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build: femiojo/contentcollector-python_web
    command: sh -c "pipenv run python3 manage.py makemigrations && 
      pipenv run python3 manage.py migrate && 
      pipenv python3 manage.py runserver"
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db