version: "3"

services:
  db:
    image: postgres:13
    env_file:
      - ./.env.prod.db
  web:
    build: .
    command: sh -c "pipenv run python3 manage.py makemigrations && 
      pipenv run python3 manage.py migrate && 
      pipenv run python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db