version: 2

orbs:
  python: circleci/python@0.2.1

jobs:
  build-db:
    docker:
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
    steps:
      - checkout
          
  test:
    executor: python/default
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv &&
            sudo apt install libpq-dev python3.7-dev &&
            pipenv install &&
            pipenv run python manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-db
      - test