version: "3"

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build: .
    command: sh -c "pipenv run python3 manage.py makemigrations && 
      pipenv run python3 manage.py migrate && 
      pipenv run gunicorn -b 0.0.0.0:8000 --log-file ./logs/log --workers 3 config.wsgi:application"
      #pipenv run python3 manage.py collectstatic --noinput &&
    volumes:
      - .:/home/app
    ports:
      - 80:8000
      - 443:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db