# Generated by Django 3.1 on 2021-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./images')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('privacyLevel', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Personal', 'Personal')], max_length=15, verbose_name='privacy level')),
                ('categories', models.ManyToManyField(blank=True, to='collections_app.Category', verbose_name='list of categories')),
                ('collections', models.ManyToManyField(blank=True, related_name='_collection_collections_+', to='collections_app.Collection', verbose_name='list of collections')),
                ('contents', models.ManyToManyField(blank=True, to='collections_app.Content', verbose_name='list of content')),
            ],
        ),
    ]
