# Generated by Django 3.1 on 2021-03-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
