# Generated by Django 3.1 on 2021-03-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_auto_20210325_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='privacyLevel',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=15, verbose_name='privacy level'),
        ),
    ]
