# Generated by Django 3.1 on 2021-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_auto_20210315_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='contents', to='collections_app.Content', verbose_name='list of content'),
        ),
    ]
