# Generated by Django 3.1 on 2021-03-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0005_auto_20210318_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='collections_app.collection'),
            preserve_default=False,
        ),
    ]
