# Generated by Django 3.1 on 2021-03-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210309_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
