# Generated by Django 3.1 on 2021-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_category_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='categories',
            field=models.ManyToManyField(blank=True, to='content.Category', verbose_name='list of categories'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='_collection_collections_+', to='content.Collection', verbose_name='list of collections'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(blank=True, to='content.Content', verbose_name='list of content'),
        ),
    ]
